from app import app, db, Question

questions = [
    # ---------- PHISHING & SOCIAL ENGINEERING (weight 5) ----------
    {"category": "Phishing", "test_type": "pre", "pair_id": 1, "weight": 5,
     "question_text": "You get an email: 'URGENT: Your course registration is incomplete. Log in within 24 hours to avoid exam clearance cancellation: portal-login.free.site'. What should you do first?",
     "option_a": "Click the link immediately since it's urgent", "option_b": "Check the actual URL/domain and go to the official portal directly instead",
     "option_c": "Forward it to a classmate to check", "option_d": "Reply asking if it's real",
     "correct_option": "B", "explanation": "Legitimate institutions use official domains. Manufactured urgency + a suspicious domain are classic phishing signs — always navigate to the official site yourself instead of clicking the link."},
    {"category": "Phishing", "test_type": "post", "pair_id": 1, "weight": 5,
     "question_text": "You get a WhatsApp message: 'Your bank account will be suspended today. Click here to verify: bank-secure-ng.info'. What's the safest action?",
     "option_a": "Click the link to verify quickly", "option_b": "Ignore and open your bank's official app directly to check your account",
     "option_c": "Reply with your account number to confirm", "option_d": "Forward to family to warn them first",
     "correct_option": "B", "explanation": "Same pattern as portal phishing: urgency + unofficial domain. Always go directly to the official app/site, never through a link in the message."},

    {"category": "Phishing", "test_type": "pre", "pair_id": 2, "weight": 5,
     "question_text": "An email claiming to be from your university's IT department asks you to 'confirm your login' by entering your student portal username and password on a linked page. What should concern you most?",
     "option_a": "The email has a logo, so it must be real", "option_b": "IT departments rarely ask you to enter your password via an email link",
     "option_c": "It's addressed to you by name", "option_d": "It was sent during working hours",
     "correct_option": "B", "explanation": "Legitimate IT/admin teams never request your password through email links. This is credential harvesting — a fake page designed to steal your login."},
    {"category": "Phishing", "test_type": "post", "pair_id": 2, "weight": 5,
     "question_text": "A message claiming to be from your email provider says your account will be deleted unless you 'verify' by entering your password on a linked form. What's the red flag?",
     "option_a": "The message is in English", "option_b": "Providers don't ask you to enter your password on external forms",
     "option_c": "It has an urgent subject line", "option_d": "It includes a company logo",
     "correct_option": "B", "explanation": "Same credential-harvesting pattern — real companies never collect your password through a form outside their official site."},

    {"category": "Phishing", "test_type": "pre", "pair_id": 3, "weight": 3,
     "question_text": "You receive a job offer email with several spelling errors, a generic greeting ('Dear Applicant'), and a request to click a link to 'accept the offer'. What does this suggest?",
     "option_a": "It's normal for real companies to have typos", "option_b": "These are common signs of a scam or phishing attempt",
     "option_c": "You should reply immediately to secure the job", "option_d": "It's fine as long as no money is requested yet",
     "correct_option": "B", "explanation": "Poor grammar, generic greetings, and urgency to click are classic low-effort phishing indicators."},
    {"category": "Phishing", "test_type": "post", "pair_id": 3, "weight": 3,
     "question_text": "A scholarship award message has spelling mistakes, addresses you as 'Dear Student', and pressures you to click a link 'before the offer expires today'. What should you think?",
     "option_a": "It's likely a scam given these signs", "option_b": "It must be real since it mentions a scholarship",
     "option_c": "Click quickly since time is limited", "option_d": "Share it publicly so others can apply too",
     "correct_option": "A", "explanation": "Generic greetings, poor grammar, and artificial urgency together are strong scam indicators, regardless of the topic."},

    # ---------- PASSWORD, MFA & OTP SECURITY (weight 5) ----------
    {"category": "Password & MFA", "test_type": "pre", "pair_id": 4, "weight": 5,
     "question_text": "A classmate messages you on WhatsApp: 'I accidentally sent my 6-digit confirmation code to your number, please forward it to me.' What should you do?",
     "option_a": "Forward the code since they're a classmate", "option_b": "Refuse — that code is for YOUR account, not theirs",
     "option_c": "Ask them to pay you first", "option_d": "Forward it but ask them to explain why",
     "correct_option": "B", "explanation": "This is the classic WhatsApp account takeover trick. That code was sent to verify YOUR account — sharing it lets an attacker take over your account."},
    {"category": "Password & MFA", "test_type": "post", "pair_id": 4, "weight": 5,
     "question_text": "Someone claiming to be from your bank calls and asks you to read out the OTP you just received to 'verify a transaction'. What should you do?",
     "option_a": "Read it out since they claim to be your bank", "option_b": "Refuse — banks never ask you to read out OTPs over the phone",
     "option_c": "Read half of it as a compromise", "option_d": "Ask them to call back later then give it",
     "correct_option": "B", "explanation": "OTPs are meant only for you. No legitimate bank or service will ever ask you to read one aloud or forward it."},

    {"category": "Password & MFA", "test_type": "pre", "pair_id": 5, "weight": 3,
     "question_text": "You use the same password for your email, social media, and bank app. What's the main risk?",
     "option_a": "No risk if the password is long", "option_b": "If one account is breached, all your accounts become vulnerable",
     "option_c": "It's fine as long as you remember it", "option_d": "Reusing passwords speeds up login only",
     "correct_option": "B", "explanation": "Password reuse means one leaked account can cascade into every other account using the same credentials."},
    {"category": "Password & MFA", "test_type": "post", "pair_id": 5, "weight": 3,
     "question_text": "A website you rarely use gets hacked and your password leaks. You used that same password for your student portal. What's the safest next step?",
     "option_a": "Do nothing since the portal wasn't hacked directly", "option_b": "Immediately change your portal password (and any account sharing it)",
     "option_c": "Wait to see if anything happens", "option_d": "Only worry if you get a suspicious email",
     "correct_option": "B", "explanation": "Attackers test leaked passwords across other sites (credential stuffing). Change shared passwords immediately after any breach."},

    {"category": "Password & MFA", "test_type": "pre", "pair_id": 6, "weight": 3,
     "question_text": "What's the main benefit of enabling two-factor/multi-factor authentication (2FA/MFA) on your accounts?",
     "option_a": "It makes login slower for no reason", "option_b": "It adds a second layer of protection even if your password is stolen",
     "option_c": "It replaces the need for a password", "option_d": "It's only useful for banking apps",
     "correct_option": "B", "explanation": "MFA means a stolen password alone isn't enough to access your account — the attacker also needs your second factor (e.g., OTP)."},
    {"category": "Password & MFA", "test_type": "post", "pair_id": 6, "weight": 3,
     "question_text": "Your friend says MFA is 'unnecessary stress' and just uses passwords. What would you tell them?",
     "option_a": "They're right, passwords alone are enough", "option_b": "MFA significantly reduces the risk of account takeover even if the password leaks",
     "option_c": "MFA is only for companies, not individuals", "option_d": "MFA is outdated technology",
     "correct_option": "B", "explanation": "Even strong passwords can leak. MFA is one of the single most effective protections against account takeover."},

    # ---------- MOBILE & DEVICE SECURITY (weight 3) ----------
    {"category": "Mobile Security", "test_type": "pre", "pair_id": 7, "weight": 3,
     "question_text": "A website offers a 'free' version of a paid app as an APK download instead of through the Play Store. What's the risk?",
     "option_a": "No risk, APKs are always safe", "option_b": "Sideloaded APKs can contain malware not screened by official app stores",
     "option_c": "It's only risky on iPhones", "option_d": "APKs are just a faster download method",
     "correct_option": "B", "explanation": "Apps from outside official stores skip security screening and are a common way malware gets installed."},
    {"category": "Mobile Security", "test_type": "post", "pair_id": 7, "weight": 3,
     "question_text": "A friend sends you a game 'cracked' version as a direct file instead of from the app store, claiming it unlocks premium features for free. What should you do?",
     "option_a": "Install it since it's from a friend", "option_b": "Avoid installing it — unofficial cracked files are a common malware source",
     "option_c": "Install it but scan it after", "option_d": "Only install if the friend says it's safe",
     "correct_option": "B", "explanation": "Cracked/unofficial app files are one of the most common ways malware spreads, regardless of the source recommending them."},

    {"category": "Mobile Security", "test_type": "pre", "pair_id": 8, "weight": 3,
     "question_text": "You want to check your bank balance while connected to free public Wi-Fi at a cafe. What's the safest approach?",
     "option_a": "Use the public Wi-Fi freely, it's convenient", "option_b": "Avoid sensitive activity like banking on public Wi-Fi, use mobile data instead",
     "option_c": "Public Wi-Fi is safe if the cafe is popular", "option_d": "Only avoid it if the Wi-Fi has no password",
     "correct_option": "B", "explanation": "Public Wi-Fi can be intercepted or spoofed by attackers. Sensitive activity like banking is safer on mobile data or a trusted network."},
    {"category": "Mobile Security", "test_type": "post", "pair_id": 8, "weight": 3,
     "question_text": "You're at the airport and need to log into your student portal. Free airport Wi-Fi is available. What's the safer choice?",
     "option_a": "Use the free Wi-Fi, airports are secure", "option_b": "Use mobile data if possible, or a VPN if you must use public Wi-Fi",
     "option_c": "Use whichever network has the strongest signal", "option_d": "It doesn't matter for a student portal",
     "correct_option": "B", "explanation": "Any public network carries interception risk. Mobile data or a VPN reduces exposure for login credentials."},

    {"category": "Mobile Security", "test_type": "pre", "pair_id": 9, "weight": 1,
     "question_text": "Your phone keeps showing 'update available' notifications for months and you keep dismissing them. What's the risk?",
     "option_a": "No risk, updates are just cosmetic", "option_b": "Updates often patch security vulnerabilities — delaying them leaves you exposed",
     "option_c": "Updates only add new emojis", "option_d": "Only matters for laptops, not phones",
     "correct_option": "B", "explanation": "Security patches are a major part of software updates. Delaying updates leaves known vulnerabilities open on your device."},
    {"category": "Mobile Security", "test_type": "post", "pair_id": 9, "weight": 1,
     "question_text": "An app on your phone hasn't been updated in over a year and still works fine. Should you be concerned?",
     "option_a": "No, if it works it's fine", "option_b": "Yes, outdated apps may have unpatched security flaws",
     "option_c": "Only if the app crashes", "option_d": "Only paid apps need updates",
     "correct_option": "B", "explanation": "An app working normally doesn't mean it's secure — unpatched vulnerabilities can exist invisibly until exploited."},

    # ---------- MALWARE & SAFE BROWSING (weight 3) ----------
    {"category": "Malware & Browsing", "test_type": "pre", "pair_id": 10, "weight": 3,
     "question_text": "You want a textbook PDF but it's paid. A site offers a 'cracked' free download. What's the risk?",
     "option_a": "No risk, it's just a PDF", "option_b": "Pirated files are a common way malware is disguised and distributed",
     "option_c": "Only risky if the file is an .exe", "option_d": "Risk only applies to software, not documents",
     "correct_option": "B", "explanation": "Pirated content (including disguised files) is a well-known malware distribution method, even when it looks like a document."},
    {"category": "Malware & Browsing", "test_type": "post", "pair_id": 10, "weight": 3,
     "question_text": "You find a site offering a 'free' cracked version of paid software you need for a class project. What should you consider?",
     "option_a": "Download it since it saves money", "option_b": "Avoid it — cracked software is a common malware vector",
     "option_c": "Only risky if it asks for payment", "option_d": "Safe if the site looks professional",
     "correct_option": "B", "explanation": "A professional-looking site doesn't guarantee safety. Cracked software remains one of the highest-risk download categories."},

    {"category": "Malware & Browsing", "test_type": "pre", "pair_id": 11, "weight": 3,
     "question_text": "A pop-up appears saying 'Your device is infected! Click here to scan now.' What should you do?",
     "option_a": "Click it immediately to fix the infection", "option_b": "Close it without clicking — this is a common scare-tactic malware trick",
     "option_c": "Share it with friends to warn them", "option_d": "Enter your card details to unlock the 'full scan'",
     "correct_option": "B", "explanation": "These 'scareware' pop-ups are designed to panic you into clicking, which usually installs the very malware it claims to remove."},
    {"category": "Malware & Browsing", "test_type": "post", "pair_id": 11, "weight": 3,
     "question_text": "A browser tab suddenly shows 'Warning! Virus detected, call this number immediately' with a loud alert sound. What's the safest response?",
     "option_a": "Call the number for help", "option_b": "Close the tab/browser without calling or clicking anything",
     "option_c": "Click 'scan now' to be sure", "option_d": "Restart your phone and call the number after",
     "correct_option": "B", "explanation": "Real operating systems don't alert you this way. This is a scare tactic to get you to call a scam number or click a malicious link."},

    {"category": "Malware & Browsing", "test_type": "pre", "pair_id": 12, "weight": 3,
     "question_text": "You receive an email with an attachment named 'Invoice.pdf.exe' from an unknown sender. What should you do?",
     "option_a": "Open it since it's labeled as a PDF", "option_b": "Don't open it — the .exe extension means it's an executable program, not a real PDF",
     "option_c": "Forward it to IT after opening it", "option_d": "Open it in a text editor to check first",
     "correct_option": "B", "explanation": "A double extension like '.pdf.exe' is a classic disguise trick — it's actually a runnable program, likely malware."},
    {"category": "Malware & Browsing", "test_type": "post", "pair_id": 12, "weight": 3,
     "question_text": "You get a message with a file called 'Result_Slip.docx.scr' from someone you don't recognize. What should concern you?",
     "option_a": "Nothing, it's probably just your result", "option_b": "The .scr extension means it's an executable file disguised as a document",
     "option_c": "Open it only on a different device", "option_d": "It's fine since it mentions results",
     "correct_option": "B", "explanation": "'.scr' files are executable screensaver files often used to disguise malware as documents."},

    # ---------- SOCIAL MEDIA & PRIVACY (weight 5 for sextortion, 3 otherwise) ----------
    {"category": "Social Media & Privacy", "test_type": "pre", "pair_id": 13, "weight": 3,
     "question_text": "You post your flight details and travel dates publicly on Instagram before a trip. What's the risk?",
     "option_a": "No risk, it's exciting to share", "option_b": "It reveals when your home will be empty and can invite theft or stalking",
     "option_c": "Only a risk for celebrities", "option_d": "Risk only applies to international trips",
     "correct_option": "B", "explanation": "Publicly sharing travel plans can signal when your home is unoccupied, or make you a target for stalking."},
    {"category": "Social Media & Privacy", "test_type": "post", "pair_id": 13, "weight": 3,
     "question_text": "You tag your exact location at a friend's house party in real-time on social media. What's a risk of this habit?",
     "option_a": "No risk, friends will see it's fun", "option_b": "Real-time location tagging can reveal patterns that enable stalking or targeting",
     "option_c": "Only a risk if you're famous", "option_d": "It's only risky at night",
     "correct_option": "B", "explanation": "Consistent real-time location sharing builds a pattern attackers or stalkers can exploit."},

    {"category": "Social Media & Privacy", "test_type": "pre", "pair_id": 14, "weight": 5,
     "question_text": "A new attractive contact you just met online quickly builds a close relationship, then asks for intimate photos, later threatening to share them unless you pay. What is this?",
     "option_a": "A normal relationship misunderstanding", "option_b": "Sextortion — a serious crime you should report, not pay",
     "option_c": "Something to handle by paying quickly and quietly", "option_d": "Nothing to worry about if you delete the chat",
     "correct_option": "B", "explanation": "This is sextortion, a rapidly growing scam. Paying often leads to repeated demands — report to platform and trusted authorities instead."},
    {"category": "Social Media & Privacy", "test_type": "post", "pair_id": 14, "weight": 5,
     "question_text": "Someone you matched with online very quickly asks you to move the conversation to a private app and share personal photos 'to prove trust'. What should you do?",
     "option_a": "Comply quickly to build trust", "option_b": "Be cautious — rapid trust-building followed by pressure for private content is a common scam pattern",
     "option_c": "Share only a few photos as a compromise", "option_d": "Ignore since it's probably harmless",
     "correct_option": "B", "explanation": "Fast-moving intimacy plus pressure for private content is a well-documented sextortion setup pattern."},

    {"category": "Social Media & Privacy", "test_type": "pre", "pair_id": 15, "weight": 3,
     "question_text": "Your social media profile is set to fully public, showing your phone number, school, and daily routine. What should you do?",
     "option_a": "Leave it, more visibility is good", "option_b": "Restrict privacy settings to limit who can see personal details",
     "option_c": "Only worry about your photos", "option_d": "Public profiles are always safe on verified platforms",
     "correct_option": "B", "explanation": "Publicly visible personal details make it easier for scammers or stalkers to build a profile on you for targeting."},
    {"category": "Social Media & Privacy", "test_type": "post", "pair_id": 15, "weight": 3,
     "question_text": "You notice your old social media posts still show your full date of birth and hometown publicly. What's the concern?",
     "option_a": "None, old posts don't matter", "option_b": "This info can be used for identity theft or answering your security questions",
     "option_c": "Only a risk if you're currently active", "option_d": "It's fine since it's old information",
     "correct_option": "B", "explanation": "Date of birth and hometown are common security question answers and identity-verification data — old posts are still exploitable."},

    # ---------- FINANCIAL / FINTECH SCAMS (weight 5) ----------
    {"category": "Financial Scams", "test_type": "pre", "pair_id": 16, "weight": 5,
     "question_text": "You receive an SMS: 'You have received ₦50,000 credit alert' from an unknown number, followed by a call asking you to 'refund' a mistaken transfer. What's happening?",
     "option_a": "A genuine bank error you should fix immediately", "option_b": "A common scam — no money was actually sent, and the 'refund' goes to the scammer",
     "option_c": "You should refund half to be safe", "option_d": "Ignore the SMS but keep the call going",
     "correct_option": "B", "explanation": "This is the fake credit alert scam — no real money moves, but victims send genuine funds as a 'refund'. Always verify directly in your bank app."},
    {"category": "Financial Scams", "test_type": "post", "pair_id": 16, "weight": 5,
     "question_text": "A seller tells you they've sent payment via bank transfer and shows you an alert screenshot, asking you to release goods before you check your actual bank app. What should you do?",
     "option_a": "Trust the screenshot and release goods", "option_b": "Confirm the credit directly in your bank app before releasing anything",
     "option_c": "Release half the goods first", "option_d": "Ask for the screenshot again as proof",
     "correct_option": "B", "explanation": "Screenshots can be faked. Always verify funds have actually landed in your account via your own bank app, not a screenshot."},

    {"category": "Financial Scams", "test_type": "pre", "pair_id": 17, "weight": 5,
     "question_text": "A Telegram channel offers $50/day for 'social media review tasks' but asks you to pay a ₦3,000 registration fee or buy crypto first to 'unlock' paid tasks. What should you do?",
     "option_a": "Pay the fee since the pay sounds good", "option_b": "Avoid it — legitimate jobs never require you to pay to start earning",
     "option_c": "Pay a smaller amount to test it", "option_d": "Ask others in the channel if it's safe",
     "correct_option": "B", "explanation": "Real employers never require upfront payment to access work. This is a task-scam designed to collect fees from many victims."},
    {"category": "Financial Scams", "test_type": "post", "pair_id": 17, "weight": 5,
     "question_text": "An online 'side hustle' promises daily earnings for rating products, but requires you to deposit money first to 'unlock higher-paying tasks'. What's the red flag?",
     "option_a": "Nothing, deposits are normal for side hustles", "option_b": "Requiring you to pay/deposit money to earn is a hallmark of a scam",
     "option_c": "Only risky if the amount is large", "option_d": "It's fine if the app looks professional",
     "correct_option": "B", "explanation": "Any 'job' that requires paying to unlock earning potential is structured as a scam, regardless of how professional it looks."},

    {"category": "Financial Scams", "test_type": "pre", "pair_id": 18, "weight": 3,
     "question_text": "A message from an unknown number claims you've won a ₦50,000 giveaway from your bank and asks you to click a link to claim it. What should you do?",
     "option_a": "Click the link to claim your prize", "option_b": "Ignore it — unsolicited giveaway messages are almost always scams",
     "option_c": "Reply asking for more details first", "option_d": "Forward it to friends so they can also claim",
     "correct_option": "B", "explanation": "Unsolicited 'you've won' messages are one of the oldest and most common scam formats — legitimate giveaways don't work this way."},
    {"category": "Financial Scams", "test_type": "post", "pair_id": 18, "weight": 3,
     "question_text": "You get a Facebook message saying you've been randomly selected for a network promo cash prize, and you just need to 'verify' your account details to receive it. What should you do?",
     "option_a": "Verify your details to claim the prize", "option_b": "Treat it as a scam and do not provide any details",
     "option_c": "Verify only your name, not other details", "option_d": "Ask the page for official documentation first, then verify",
     "correct_option": "B", "explanation": "Random 'you've been selected' promos requesting personal/account details are a standard scam pattern — don't engage."},

    # ---------- DATA PRIVACY / IDENTITY (weight 5) ----------
    {"category": "Data Privacy", "test_type": "pre", "pair_id": 19, "weight": 5,
     "question_text": "A 'government scholarship' form asks for your full name, NIN, BVN, bank account number, and your portal login password. What are the major red flags?",
     "option_a": "Nothing unusual for a scholarship form", "option_b": "Legitimate forms never need your BVN alongside your login password — this combination enables identity theft",
     "option_c": "Only the password request is a concern", "option_d": "Only the BVN request is a concern",
     "correct_option": "B", "explanation": "No legitimate scholarship needs your account password, and bundling NIN/BVN with login credentials is a major identity theft red flag."},
    {"category": "Data Privacy", "test_type": "post", "pair_id": 19, "weight": 5,
     "question_text": "An online 'grant application' asks for your NIN, date of birth, and your email password to 'verify eligibility'. What should concern you?",
     "option_a": "Nothing, verification requires personal info", "option_b": "No legitimate verification process ever requires your email password",
     "option_c": "Only concerning if it's not government-branded", "option_d": "It's fine if the form looks official",
     "correct_option": "B", "explanation": "Passwords are never required for identity verification — this is a data harvesting attempt disguised as a legitimate process."},

    {"category": "Data Privacy", "test_type": "pre", "pair_id": 20, "weight": 5,
     "question_text": "Someone calls claiming to be your bank's agent and asks you to confirm your BVN 'to prevent your account from being blocked'. What should you do?",
     "option_a": "Provide your BVN since it's your bank", "option_b": "Refuse — banks don't request BVN verification by phone this way, call your bank directly instead",
     "option_c": "Give a partial BVN", "option_d": "Ask them to send an SMS with the request first",
     "correct_option": "B", "explanation": "Banks don't call to request your BVN this way. If concerned, hang up and call your bank's official number directly."},
    {"category": "Data Privacy", "test_type": "post", "pair_id": 20, "weight": 5,
     "question_text": "A caller claims to be from NIMC and asks you to confirm your NIN and linked phone number 'for verification', citing a deadline. What's the safe response?",
     "option_a": "Provide the info since they mentioned a deadline", "option_b": "Decline and verify independently through NIMC's official channels",
     "option_c": "Give the NIN but not the phone number", "option_d": "Ask them to call back later then provide it",
     "correct_option": "B", "explanation": "Urgency plus unsolicited requests for identity numbers is a classic pretext for identity theft — always verify independently."},

    # ---------- INCIDENT RESPONSE (weight 1-3, knowledge-based) ----------
    {"category": "Incident Response", "test_type": "pre", "pair_id": 21, "weight": 3,
     "question_text": "You realize you just entered your password on a fake login page. What should you do immediately?",
     "option_a": "Do nothing, it's probably fine", "option_b": "Change that password immediately (and anywhere else you reused it), and enable MFA",
     "option_c": "Wait a few days to see if anything happens", "option_d": "Only worry if you notice suspicious activity",
     "correct_option": "B", "explanation": "Acting fast limits damage — change the compromised password everywhere it was reused and add MFA where possible."},
    {"category": "Incident Response", "test_type": "post", "pair_id": 21, "weight": 3,
     "question_text": "You suspect your email account has been accessed by someone else. What's your first step?",
     "option_a": "Ignore it unless you see obvious changes", "option_b": "Change your password immediately and check/revoke active sessions or connected devices",
     "option_c": "Delete the account entirely", "option_d": "Wait for a notification from the provider",
     "correct_option": "B", "explanation": "Immediate password change plus reviewing active sessions cuts off the attacker's access as quickly as possible."},

    {"category": "Incident Response", "test_type": "pre", "pair_id": 22, "weight": 1,
     "question_text": "You receive a suspicious SMS claiming to be from your bank with a scam link. What's a good practice, even if you didn't click it?",
     "option_a": "Ignore it completely and do nothing", "option_b": "Report/block the number and report it to your bank if it impersonates them",
     "option_c": "Reply telling them to stop", "option_d": "Forward it to everyone as a joke",
     "correct_option": "B", "explanation": "Reporting suspicious messages helps your bank/telecom track and block scam campaigns, protecting others too."},
    {"category": "Incident Response", "test_type": "post", "pair_id": 22, "weight": 1,
     "question_text": "You notice a scam job posting impersonating a real company on social media. What's a responsible action?",
     "option_a": "Ignore it, it's not your problem", "option_b": "Report the post/page to the platform and to the real company if possible",
     "option_c": "Comment publicly arguing with the scammer", "option_d": "Share it around to 'expose' them yourself",
     "correct_option": "B", "explanation": "Reporting through official channels is safer and more effective than public engagement, which can tip off scammers to evade detection."},
]

def seed():
    with app.app_context():
        # Avoid duplicate seeding
        if Question.query.first():
            print("Questions already exist. Skipping seeding.")
            return
        for q in questions:
            db.session.add(Question(**q))
        db.session.commit()
        print(f"Seeded {len(questions)} questions successfully.")

if __name__ == '__main__':
    seed()